/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COMMON_COMMON_PB_H_INCLUDED
#define PB_COMMON_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _common_error_code {
    common_error_code_SUCCESS = 0,
    common_error_code_FAILED = 1
} common_error_code;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _common_error_code_MIN common_error_code_SUCCESS
#define _common_error_code_MAX common_error_code_FAILED
#define _common_error_code_ARRAYSIZE ((common_error_code)(common_error_code_FAILED+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
