/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FRAME_PB_H_INCLUDED
#define PB_FRAME_PB_H_INCLUDED
#include <pb.h>
#include "ota.pb.h"
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Frame {
    pb_size_t which_load;
    union {
        ota_start_req ota_start_req; /* OTA开始请求 方向 服务器 -> 设备 */
        ota_start_res ota_start_res; /* OTA开始响应 方向 设备 -> 服务器 */
        ota_data_send ota_data_send; /* OTA数据发送       方向 服务器 -> 设备 */
        ota_data_recv ota_data_recv; /* OTA数据接收结果   方向 设备 -> 服务器 */
        ota_result_get_req ota_result_get_req; /* OTA结果获取       方向 服务器 -> 设备 */
        ota_result_get_res ota_result_get_res; /* OTA结果上传       方向 设备 -> 服务器 */
    } load;
} Frame;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Frame_init_default                       {0, {ota_start_req_init_default}}
#define Frame_init_zero                          {0, {ota_start_req_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Frame_ota_start_req_tag                  1
#define Frame_ota_start_res_tag                  2
#define Frame_ota_data_send_tag                  3
#define Frame_ota_data_recv_tag                  4
#define Frame_ota_result_get_req_tag             5
#define Frame_ota_result_get_res_tag             6

/* Struct field encoding specification for nanopb */
#define Frame_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (load,ota_start_req,load.ota_start_req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (load,ota_start_res,load.ota_start_res),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (load,ota_data_send,load.ota_data_send),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (load,ota_data_recv,load.ota_data_recv),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (load,ota_result_get_req,load.ota_result_get_req),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (load,ota_result_get_res,load.ota_result_get_res),   6)
#define Frame_CALLBACK NULL
#define Frame_DEFAULT NULL
#define Frame_load_ota_start_req_MSGTYPE ota_start_req
#define Frame_load_ota_start_res_MSGTYPE ota_start_res
#define Frame_load_ota_data_send_MSGTYPE ota_data_send
#define Frame_load_ota_data_recv_MSGTYPE ota_data_recv
#define Frame_load_ota_result_get_req_MSGTYPE ota_result_get_req
#define Frame_load_ota_result_get_res_MSGTYPE ota_result_get_res

extern const pb_msgdesc_t Frame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Frame_fields &Frame_msg

/* Maximum encoded size of messages (where known) */
#define FRAME_PB_H_MAX_SIZE                      Frame_size
#define Frame_size                               1030

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
