/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OTA_OTA_PB_H_INCLUDED
#define PB_OTA_OTA_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ota_error_code {
    ota_error_code_OTA_ERROR_SUCCESS = 0, /* 成功 */
    ota_error_code_OTA_ERROR_FILE_NOT_FOUND = 1, /* 文件不存在 */
    ota_error_code_OTA_ERROR_FILE_SIZE_TOO_LARGE = 2, /* 文件过大 */
    ota_error_code_OTA_ERROR_FILE_CRC32_ERROR = 3, /* 文件CRC32错误 */
    ota_error_code_OTA_ERROR_FILE_VERSION_ERROR = 4, /* 版本号错误 */
    ota_error_code_OTA_ERROR_FILE_NOT_SUPPORT = 5 /* 文件不支持 */
} ota_error_code;

/* Struct definitions */
/* OTA 开始请求 */
typedef struct _ota_start_req {
    uint32_t file_size; /* 文件大小 */
    uint32_t file_crc32; /* 文件CRC32 */
    char version[40]; /* 版本号 */
} ota_start_req;

/* OTA 启动应答 */
typedef struct _ota_start_res {
    uint32_t chunk_size; /* 数据块大小 */
    ota_error_code error_code;
} ota_start_res;

typedef PB_BYTES_ARRAY_T(1024) ota_data_send_data_t;
/* OTA 数据包 */
typedef struct _ota_data_send {
    ota_data_send_data_t data; /* 数据 */
} ota_data_send;

/* OTA 数据应答 */
typedef struct _ota_data_recv {
    uint32_t last_vaild_chunk; /* 最后有效数据块 */
    ota_error_code error_code; /* 错误码 */
} ota_data_recv;

/* OTA 获取OTA结果 */
typedef struct _ota_result_get_req {
    char dummy_field;
} ota_result_get_req;

/* OTA 结果 */
typedef struct _ota_result_get_res {
    ota_error_code error_code;
} ota_result_get_res;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ota_error_code_MIN ota_error_code_OTA_ERROR_SUCCESS
#define _ota_error_code_MAX ota_error_code_OTA_ERROR_FILE_NOT_SUPPORT
#define _ota_error_code_ARRAYSIZE ((ota_error_code)(ota_error_code_OTA_ERROR_FILE_NOT_SUPPORT+1))


#define ota_start_res_error_code_ENUMTYPE ota_error_code


#define ota_data_recv_error_code_ENUMTYPE ota_error_code


#define ota_result_get_res_error_code_ENUMTYPE ota_error_code


/* Initializer values for message structs */
#define ota_start_req_init_default               {0, 0, ""}
#define ota_start_res_init_default               {0, _ota_error_code_MIN}
#define ota_data_send_init_default               {{0, {0}}}
#define ota_data_recv_init_default               {0, _ota_error_code_MIN}
#define ota_result_get_req_init_default          {0}
#define ota_result_get_res_init_default          {_ota_error_code_MIN}
#define ota_start_req_init_zero                  {0, 0, ""}
#define ota_start_res_init_zero                  {0, _ota_error_code_MIN}
#define ota_data_send_init_zero                  {{0, {0}}}
#define ota_data_recv_init_zero                  {0, _ota_error_code_MIN}
#define ota_result_get_req_init_zero             {0}
#define ota_result_get_res_init_zero             {_ota_error_code_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ota_start_req_file_size_tag              1
#define ota_start_req_file_crc32_tag             2
#define ota_start_req_version_tag                3
#define ota_start_res_chunk_size_tag             1
#define ota_start_res_error_code_tag             2
#define ota_data_send_data_tag                   1
#define ota_data_recv_last_vaild_chunk_tag       1
#define ota_data_recv_error_code_tag             2
#define ota_result_get_res_error_code_tag        1

/* Struct field encoding specification for nanopb */
#define ota_start_req_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         1) \
X(a, STATIC,   SINGULAR, UINT32,   file_crc32,        2) \
X(a, STATIC,   SINGULAR, STRING,   version,           3)
#define ota_start_req_CALLBACK NULL
#define ota_start_req_DEFAULT NULL

#define ota_start_res_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size,        1) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        2)
#define ota_start_res_CALLBACK NULL
#define ota_start_res_DEFAULT NULL

#define ota_data_send_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define ota_data_send_CALLBACK NULL
#define ota_data_send_DEFAULT NULL

#define ota_data_recv_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   last_vaild_chunk,   1) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        2)
#define ota_data_recv_CALLBACK NULL
#define ota_data_recv_DEFAULT NULL

#define ota_result_get_req_FIELDLIST(X, a) \

#define ota_result_get_req_CALLBACK NULL
#define ota_result_get_req_DEFAULT NULL

#define ota_result_get_res_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        1)
#define ota_result_get_res_CALLBACK NULL
#define ota_result_get_res_DEFAULT NULL

extern const pb_msgdesc_t ota_start_req_msg;
extern const pb_msgdesc_t ota_start_res_msg;
extern const pb_msgdesc_t ota_data_send_msg;
extern const pb_msgdesc_t ota_data_recv_msg;
extern const pb_msgdesc_t ota_result_get_req_msg;
extern const pb_msgdesc_t ota_result_get_res_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ota_start_req_fields &ota_start_req_msg
#define ota_start_res_fields &ota_start_res_msg
#define ota_data_send_fields &ota_data_send_msg
#define ota_data_recv_fields &ota_data_recv_msg
#define ota_result_get_req_fields &ota_result_get_req_msg
#define ota_result_get_res_fields &ota_result_get_res_msg

/* Maximum encoded size of messages (where known) */
#define OTA_OTA_PB_H_MAX_SIZE                    ota_data_send_size
#define ota_data_recv_size                       8
#define ota_data_send_size                       1027
#define ota_result_get_req_size                  0
#define ota_result_get_res_size                  2
#define ota_start_req_size                       53
#define ota_start_res_size                       8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
