/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ota.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ota_start_req, ota_start_req, AUTO)


PB_BIND(ota_start_res, ota_start_res, AUTO)


PB_BIND(ota_data_send, ota_data_send, 2)


PB_BIND(ota_data_recv, ota_data_recv, AUTO)


PB_BIND(ota_result_get_req, ota_result_get_req, AUTO)


PB_BIND(ota_result_get_res, ota_result_get_res, AUTO)





