/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TEST_TEST_PB_H_INCLUDED
#define PB_TEST_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) test_file_info_data_t;
typedef struct _test_file_info {
    uint32_t file_size;
    pb_size_t file_hash_count;
    uint32_t file_hash[32];
    char version[40];
    test_file_info_data_t data;
} test_file_info;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define test_file_info_init_default              {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, "", {0, {0}}}
#define test_file_info_init_zero                 {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, "", {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define test_file_info_file_size_tag             1
#define test_file_info_file_hash_tag             2
#define test_file_info_version_tag               3
#define test_file_info_data_tag                  4

/* Struct field encoding specification for nanopb */
#define test_file_info_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         1) \
X(a, STATIC,   REPEATED, UINT32,   file_hash,         2) \
X(a, STATIC,   SINGULAR, STRING,   version,           3) \
X(a, STATIC,   SINGULAR, BYTES,    data,              4)
#define test_file_info_CALLBACK NULL
#define test_file_info_DEFAULT NULL

extern const pb_msgdesc_t test_file_info_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define test_file_info_fields &test_file_info_msg

/* Maximum encoded size of messages (where known) */
#define TEST_TEST_PB_H_MAX_SIZE                  test_file_info_size
#define test_file_info_size                      1266

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
